### ISSUE TITLE
Install.sh script does not build functional flax-blockchain on Ubuntu [BUG]

### ISSUE THREAD

**Issue by whitetechnologies** [Flax-Network/flax-blockchain#3]
**Describe the bug**
Cannot build functional Flax on Ubuntu via CLI

**To Reproduce**
git clone https://github.com/Flax-Network/flax-blockchain.git -b main--recurse-submodules
cd flax-blockchain

sh install.sh

. ./activate

[At this point, there is no activate shortcut built in the flax-blockchain folder. Nor is there a flax-blockchain/venv folder (where the activate script actually lives. If we modify the chia-blockchain activate script (replace chia with flax) and copy the venv folder, the activate script WILL work and load the virtual environment (venv). However, when attempting to run any flax CLI command, we get an error "flax is not a recognized command"

**Expected behavior**
As per https://flaxnetwork.org/download.html, Flax client should be able to be built from code, just by replacing "chia" with "flax"

**Desktop (please complete the following information):**

Ubuntu 2.04

**Additional context**

**Comment by Leozolt** [comment]
git clone https://github.com/Flax-Network/flax-blockchain.git --recurse-submodules

works fine for me.

-b main gives an error for me

**Comment by whitetechnologies** [comment]
Are you saying you got it to run correctly using that way? Or just that you were able to pull the repo? I tried it your way (without specifying the branch) and it's the same issue. Cloning from git works fine, install.sh runs and builds everything in flax-blockchain directory but no /venv directory is created and no activate script available. 

The only thing I can think of is during install.sh I get an error for ppa repo. But I think that was same with chia-blockchain and didn't affect anything....see error below. 

E: The repository 'http://ppa.launchpad.net/jfi/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by VisualWebTech** [comment]
I Have exactly the same issue

**Comment by Martin-Stangl** [comment]
I just did ...

git clone https://github.com/Flax-Network/flax-blockchain.git -b 0.1 --recurse-submodules
cd flax-blockchain
sh install.sh
. ./activate

... and it work fine.

On openSuSE Leap 15.3 with python3.9.
IF it was not a typo here, I would guess the issue is related to the missing space in "-b main--recurse-submodules".

**Comment by VisualWebTech** [comment]
solution on ubuntu:
go to Software & Updates
go to Other Software tab
Select http://ppa.launchpad.net/jfi/ppa/ubuntu
click remove 

then try to run  again 

sh install.sh
. ./activate

and it should work

**Comment by room101-dev** [comment]
Make sure you have python-3.7 installed and 'env' tool kit
I usually just cut&paste out the ubuntu install cmd-lines from the install.sh, as it was broken when it lived in Chia-Land.
Yep it wasn't easy to install/build Flax, but finally got it to work, most of the problem was that the python 'env' folder wasn't getting created, and without that you don't have ". ./activate", and without that you don't have 'flax'

**Comment by room101-dev** [comment]
> solution on ubuntu:
> go to Software & Updates
> go to Other Software tab
> Select http://ppa.launchpad.net/jfi/ppa/ubuntu
> click remove
> 
> then try to run again
> 
> sh install.sh
> . ./activate
> 
> and it should work

It only 'works' if you have all the 'requirements', and as you all might know the Flax people have removed all the chia install wiki stuff from the github distro, so if you aren't an expert at installing 'chia' on linux, then getting the 'flax' setup isn't going to be easy.

Probably makes the most sense if your having problems, is to fall back to a basic chia-net install, and get your 'requirements' right for your system, then come back to 'flax' and do the "install.sh", and yes it will work as you say, but there is no way a noob can get the 'requirements' right because there is no documentation, and so many of the python3.7 kit env parts must match exactly.

Most of my problems in setting up the 'flax' install were that my python3 env defaults had changed since the last time I had installed 'chia';

...

**Lastly, the install.sh never did work on CHIA-NET, as it wasn't tested, and all the conditionals had problems, its only a 3 line install that you really need, so its best to just read the install.sh cut&paste what you need out, and create your own install.sh for your linux distro.**

**Comment by whitetechnologies** [comment]
Issue was resolved. The solution is as follows: 

Install.sh script is not written correctly (by Chia devs). If you have a PPA that throws a warning in apt (for example, a PPA repo that doesn't have a release file), the default install.sh script will break. It does not skip through the warning (as it should), but instead errors out. This is not correct behavior for an install script, but is not a Flax problem, it is a Chia problem. 

SOLUTION: if you have any linux PPA repo that throws an error or warning, you have to disabled it first (explained here: https://itsfoss.com/how-to-remove-or-delete-ppas-quick-tip/). After this, the install.sh script will run correctly and finish building flax-blockchain. Then, you can run normal . ./activate and run flax commands. 

Sorry that this was such a simple fix, but I have never seen an install script not bypass an apt warning. That's basic best practice so I have no idea why chia devs did not implement this. Thank you for everyone that tried to help!
